var langs = {
    en: {
        headline: "LOYALTY PROGRAM",
        congratulationTitle: "Congratulations!",
        congratulationSubtitle: "Today you are lucky!",
        intro: "We select users to give them the opportunity to win prizes from our sponsors. Turn the wheel to see which prize you will receive!",
        btnSpin: "Push",
        totalLikes: "people like this",
        likeWord: "Like",
        commentWord: "Comment",
        commentName1: "Parjapat Sunil",
        commentText1: "Dropped Samsung Galaxy S9! Honestly, I wanted the iMac, but not today ...",
        itemDate1: "Yesterday at 08:13",
        commentName2: "Sahil John",
        commentText2: "I won 1 free spin, but I did not win a prize. Can I get another chance?",
        commentName3: "Parmar Mahesh",
        commentText3: "I just unpacked the new iMac! This is the best prize of all!",
        commentName4: "Doan Ha",
        commentText4:
            "At first I thought it was a joke, but this morning I was delivered a new Samsung Galaxy S9, I also got a T-shirt with a logo!",
        commentName5: "Alexis Shane",
        commentText5: "My iMac arrived this morning! I love it!!!",
        commentName6: "Beatrice Appiah",
        commentText6: "I won the iPad. I still do not believe that this is true!",
        commentName7: "Ranvin Hazam",
        commentText7: "I won the ipad, but I already have it, can I change the prize on the iMac?",
        show_next: "See all",
        placeholder: "Your message",
        modalMessage: "You have 1 extra spin",
        btnModal: "Try again",
        congratulationTitle2: "Congratulations!",
        congratulationSubtitle2: "You won a super prize!",
        condition:
            "You will need to complete the prize submission form or your prize will be forfeited.",
        conditionTitle: "IMPORTANT: ",
        conditions2: "Gifts can end anytime, choose faster!",
        timeTitle: "Offer valid for",
        minutes: "minutes",
        seconds: "seconds",
        prize1Title: "Prize №1",
        prize2Title: "Prize №2",
        prizePriceCommon: "Common price:",
        prizePriceYour: "Your price:",
        prizeAvailable: "Available:",
        btnChoose: "Choose",
    },
    ar: {
        headline: "برنامج الولاء",
        congratulationTitle: "تهانينا!",
        congratulationSubtitle: "أنت محظوظ اليوم!",
        intro: "نقوم باختيار مستخدمين لمنحهم فرصة الفوز بجوائز من ممولينا. قم بتدوير العجلة لتكتشف ما هي جائزتك!",
        btnSpin: "ادفع",
        totalLikes: "أشخاص مماثلين",
        likeWord: "إعجاب",
        commentWord: "تعليق",
        commentName1: "براجاباتي سونيل-Parjapat Sunil",
        commentText1: "ليس اليوم ...",
        itemDate1: "أمس، الساعة 08:13",
        commentName2: "ساحيل جون-Sahil John",
        commentText2:
            "لقد ربحت دورة مجانية واحدة ولكن لم أفز بجائزة. هل يمكنني الحصول على فرصة أخرى؟",
        commentName3: "بارمار ماهيش-Parmar Mahesh",
        commentText3: "لقد قمت للتو بفتح صندوق جهاز iMac الجديد! هذه أفضل جائزة على الإطلاق!",
        commentName4: "دوان ها-Doan Ha",
        commentText4:
            "اعتقدت أنها مزحة في بداية الأمر ، لكن هذا الصباح استلمت هاتف Samsung Galaxy S9 جديد، كما أنني حصلت على تي شيرت يحمل شعارًا!",
        commentName5: "الكسيس شين-Alexis Shane",
        commentText5: "لقد استلمت الــiMac هذا الصباح! إنه مذهل! ",
        commentName6: "بياتريس أبياه-Beatrice Appiah",
        commentText6: "لقد فزت بجهاز iPad. ما زلت لا استطيع التصديق، هل قد حدث ذلك بالفعل؟",
        commentName7: "رانفين حازم-Ranvin Hazam",
        commentText7:
            "لقد فزت بجهاز iPad ، ولكنني أمتلك واحداً بالفعل، هل يمكنني تغيير الجائزة إلى جهاز iMac؟",
        show_next: "إظهار الكل",
        placeholder: "رسائلك",
        modalMessage: "لديك دورة إضافية",
        btnModal: "حاول مرة أخرى",
        congratulationTitle2: "",
        congratulationSubtitle2: "لقد فزت بجائزة رائعة!",
        condition: "ستحتاج إلى إكمال نموذج تقديم الجائزة وإلا ستفقد جائزتك.",
        conditionTitle: "هام:",
        conditions2: "يمكن أن تنفذ الهدايا في أي وقت ، اختر بسرعة!",
        timeTitle: "العرض سائر حتى",
        minutes: "دقائق",
        seconds: "ثواني",
        prize1Title: "الجائزة الأولى",
        prize2Title: "الجائزه الثانيه",
        prizePriceCommon: "السعر الشائع:",
        prizePriceYour: "السعر الخاص:",
        prizeAvailable: "المتاح:",
        btnChoose: "اختر",
    },
    ms: {
        headline: "PROGRAM KESETIAAN",
        congratulationTitle: "TAHNIAH!",
        congratulationSubtitle: "Anda bernasib baik hari ini!",
        intro: "Kami memilih pengguna untuk memberi mereka peluang untuk memenangi hadiah dari penaja kami. Putar roda untuk melihat hadiah mana yang akan anda terima!",
        btnSpin: "Tolak",
        totalLikes: "ramai sukakan ini",
        likeWord: "Suka",
        commentWord: "Komen",
        commentName1: "Parjapat Sunil",
        commentText1:
            "Lupakan Samsung Galaxy S9! Secara jujur, saya mahukan iMac, tetapi tidak hari ini…",
        itemDate1: "Semalam jam 08:13",
        commentName2: "Sahil John",
        commentText2:
            "Saya memenangi 1 putaran percuma, tetapi saya tidak memenangi hadiah. Boleh berikan saya satu peluang lagi?",
        commentName3: "Parmar Mahesh",
        commentText3:
            "Saya baru saja membuka bungkusan iMac baru! Ini adalah hadiah terbaik dari semua!",
        commentName4: "Doan Ha",
        commentText4:
            "Pada mulanya saya menganggapnya sebagai gurauan, tetapi pagi ini saya menerima Samsung Galaxy S9 baru, saya juga mendapat kemeja-T dengan logo!",
        commentName5: "Alexis Shane",
        commentText5: "IMac saya tiba pagi ini! Saya sukakannya!!!",
        commentName6: "Beatrice Appiah",
        commentText6: "Saya memenangi iPad. Saya masih tidak percaya bahawa ini benar!",
        commentName7: "Ranvin Hazam",
        commentText7:
            "Saya memenangi ipad, tetapi saya sudah memilikinya, bolehkah saya menukar hadiah kepada iMac?",
        show_next: "Lihat semua",
        placeholder: "Mesej anda",
        modalMessage: "Anda mempunyai 1 putaran tambahan",
        btnModal: "Cuba lagi",
        congratulationTitle2: "Anda memenangi hadiah super!",
        congratulationSubtitle2:
            "Anda perlu melengkapkan borang penyerahan hadiah atau hadiah anda akan hilang.",
        condition: "Anda perlu melengkapkan borang penyerahan hadiah atau hadiah anda akan hilang.",
        conditionTitle: "PENTING:",
        conditions2: "Hadiah boleh berakhir bila-bila masa, pilih dengan lebih cepat!",
        timeTitle: "Tawaran sah untuk",
        minutes: "minit",
        seconds: "saat",
        prize1Title: "Hadiah №1",
        prize2Title: "Hadiah №2 ",
        prizePriceCommon: "Harga biasa:",
        prizePriceYour: "Harga anda:",
        prizeAvailable: "Tersedia:",
        btnChoose: "Pilih",
    },
    ko: {
        headline: "로열티 프로그램",
        congratulationTitle: "축하합니다!",
        congratulationSubtitle: "오늘 운이 참 좋습니다!",
        intro: "추첨을 통해 후원업체가 제공하는 경품을 드립니다. 돌림판을 돌리고 과연 행운이 찾아올지 시험해 보세요!",
        btnSpin: "누르기",
        totalLikes: "인기",
        likeWord: "좋아요",
        commentWord: "댓글",
        commentName1: "강지승",
        commentText1: "갤럭시 S9 당첨요! 솔직히 노린 건 아이맥인데 오늘 운이 영...",
        itemDate1: "어제 08:13",
        commentName2: "최호영",
        commentText2: "무료 돌리기 당첨되서 돌렸는데 꽝이네요. 한 번 더 못하나?",
        commentName3: "김민",
        commentText3: "이번에 나온 아이맥 떴다! 역대급 행운이로구나",
        commentName4: "하수연",
        commentText4:
            "속는 셈 치고 며칠 전에 돌렸는데 오늘 아침에 진짜 갤럭시 S9 당첨된 거 받았어요. 또 운 좋게 로고 티셔츠까지 받았습니다!",
        commentName5: "김동준",
        commentText5: "아침에 아이맥 배달 왔습니다! 진짜 진짜 감사합니다!!!",
        commentName6: "최시연",
        commentText6: "아이패드 걸렸다! 이거 실화냐!!",
        commentName7: "박지수",
        commentText7: "아이패드 있는데 아이패드 걸렸네.. 이거 아이맥으로 교환 안 되나요? ",
        show_next: "모두 보기",
        placeholder: "내 메시지",
        modalMessage: "추가 기회가 1회 있습니다",
        btnModal: "재시도",
        congratulationTitle2: "축하합니다!",
        congratulationSubtitle2: "슈퍼 경품에 당첨되었습니다!",
        condition: "경품 수령 양식을 제출하세요. 제출하지 않으면 당첨이 취소됩니다.",
        conditionTitle: "중요:",
        conditions2: "경품이 소진되면 당첨될 수 없습니다. 서둘러 참가하세요!",
        timeTitle: "제안 남은 시간",
        minutes: "분",
        seconds: "초",
        prize1Title: "1등 경품",
        prize2Title: "2등 경품",
        prizePriceCommon: "공통 보상:",
        prizePriceYour: "내 보상:",
        prizeAvailable: "이용 가능:",
        btnChoose: "선택",
    },
    el: {
        headline: "ΠΡΟΓΡΑΜΜΑ ΑΦΟΣΙΩΣΗΣ",
        congratulationTitle: "ΣΥΓΧΑΡΗΤΗΡΙΑ!",
        congratulationSubtitle: "Έχετε τύχη σήμερα!",
        intro: "Επιλέγουμε χρήστες και τους δίνουμε την ευκαιρία να κερδίσουν βραβεία από τους χορηγούς μας. Γυρίστε τον τροχό για να μάθετε ποιο έπαθλο θα λάβετε!",
        btnSpin: "Πιέστε",
        totalLikes: "άτομα που τους αρέσει",
        likeWord: "Μου αρέσει",
        commentWord: "Σχόλιο",
        commentName1: "Parjapat Sunil",
        commentText1:
            "Έτυχα το Samsung Galaxy S9! Στην πραγματικότητα ήθελα το iMac, αλλά δεν ήταν η τυχερή μου μέρα …",
        itemDate1: "Χθες στις 08:13",
        commentName2: "Sahil John",
        commentText2:
            "Κέρδισα μία δωρεάν περιστροφή, αλλά δεν κέρδισα κάποιο βραβείο. Μπορώ να έχω άλλη μία ευκαιρία; ",
        commentName3: "Parmar Mahesh",
        commentText3: "Μόλις άνοιξα το καινούργιο μου iMac! Είναι το καλύτερο έπαθλο από όλα!",
        commentName4: "Doan Ha",
        commentText4:
            "Στην αρχή νόμιζα πως ήταν κάποιο αστείο, αλλά μόλις σήμερα έλαβα ένα καινούργιο  Galaxy S9, καθώς και ένα μπλουζάκι με στάμπα!",
        commentName5: "Alexis Shane",
        commentText5: "Παρέλαβα το iMac σήμερα το πρωί! Το αγαπώ!!!",
        commentName6: "Beatrice Appiah",
        commentText6: "Κέρδισα το iPad. Δεν μπορώ να πιστέψω πως είναι αλήθεια!",
        commentName7: "Ranvin Hazam",
        commentText7:
            "Έχω κερδίσει το ipad, αλλά έχω ήδη ένα, υπάρχει περίπτωση να μπορώ να αλλάξω το έπαθλο και να πάρω ένα iMac;",
        show_next: "Προβολή όλων",
        placeholder: "Το μήνυμά σας",
        modalMessage: "Έχετε μία επιπλέον περιστροφή",
        btnModal: "Δοκιμάστε ξανά",
        congratulationTitle2: "ΣΥΓΧΑΡΗΤΗΡΙΑ!",
        congratulationSubtitle2: "Κερδίσατε ένα σούπερ έπαθλο!",
        condition:
            "Οφείλετε να συμπληρώσετε τη φόρμα υποβολής βραβείων, σε διαφορετική περίπτωση το έπαθλο σας δεν θα ισχύει.",
        conditionTitle: "ΣΗΜΑΝΤΙΚΟ:",
        conditions2: "Τα δώρα μπορεί να λήξουν ανά πάσα στιγμή, διαλέξτε γρήγορα!",
        timeTitle: "Η προσφορά ισχύει έως",
        minutes: "λεπτά",
        seconds: "δευτερόλεπτα",
        prize1Title: "Έπαθλο №1",
        prize2Title: "Έπαθλο №2",
        prizePriceCommon: "Κοινό έπαθλο:",
        prizePriceYour: "Το έπαθλό σας:",
        prizeAvailable: "Διαθεσιμότητα:",
        btnChoose: "Επιλογή",
    },
    yue: {
        headline: "獎勵計畫",
        congratulationTitle: "恭喜！",
        congratulationSubtitle: "今天您很幸運！",
        intro: "我們隨機抽選用戶，將有機會從我們的贊助商那裡贏得獎品。轉動轉盤，看看您將獲得哪個獎品！",
        btnSpin: "按此",
        totalLikes: "people like this",
        likeWord: "Like",
        commentWord: "Comment",
        commentName1: "Parjapat Sunil",
        commentText1: "Dropped Samsung Galaxy S9! Honestly, I wanted the iMac, but not today ...",
        itemDate1: "Yesterday at 08:13",
        commentName2: "Sahil John",
        commentText2: "I won 1 free spin, but I did not win a prize. Can I get another chance?",
        commentName3: "Parmar Mahesh",
        commentText3: "I just unpacked the new iMac! This is the best prize of all!",
        commentName4: "Doan Ha",
        commentText4:
            "At first I thought it was a joke, but this morning I was delivered a new Samsung Galaxy S9, I also got a T-shirt with a logo!",
        commentName5: "Alexis Shane",
        commentText5: "My iMac arrived this morning! I love it!!!",
        commentName6: "Beatrice Appiah",
        commentText6: "I won the iPad. I still do not believe that this is true!",
        commentName7: "Ranvin Hazam",
        commentText7: "I won the ipad, but I already have it, can I change the prize on the iMac?",
        show_next: "See all",
        placeholder: "Your message",
        modalMessage: "你有 1 次額外旋轉機會",
        btnModal: "再試一次",
        congratulationTitle2: "恭喜！",
        congratulationSubtitle2: "",
        condition: "您需要填寫獎品提交表，否則您的獎品將會被沒收。",
        conditionTitle: "重要提示：",
        conditions2: "禮物隨時會結束，動作要快！",
        timeTitle: "優惠有效期為",
        minutes: "分",
        seconds: "秒",
        prize1Title: "獎項 №1",
        prize2Title: "獎項 №2",
        prizePriceCommon: "市價: ",
        prizePriceYour: "折扣後您的價格:",
        prizeAvailable: "剩餘:",
        btnChoose: "選擇",
    },
    ru: {
        headline: "ПРОГРАММА ЛОЯЛЬНОСТИ",
        congratulationTitle: "Поздравляем!",
        congratulationSubtitle: "Сегодня Ваш день!",
        intro: "Мы выбираем пользователей, и даём им возможность выиграть призы от наших спонсоров. Крути колесо, чтобы увидеть свой приз!",
        btnSpin: "Толчок",
        totalLikes: " людям это понравилось",
        likeWord: "Лайк",
        commentWord: "Комментарий",
        commentName1: "Parjapat Sunil",
        commentText1:
            "Выпал Samsung Galaxy S9! Честно говоря, я хотел iMac, но видимо не сегодня ...",
        itemDate1: "Вчера в 08:13",
        commentName2: "Sahil John",
        commentText2:
            "Я получил 1 фри спин, но не выиграл приз. Моглу ли я получить еще один шанс?",
        commentName3: "Parmar Mahesh",
        commentText3: "Я только что распаковал новый iMac! Это самый лучший приз из всех!",
        commentName4: "Doan Ha",
        commentText4:
            "Сначала я подумал, что это шутка, но сегодня утром мне доставили новый Samsung Galaxy S9, а так же футболку с логотипом!",
        commentName5: "Alexis Shane",
        commentText5: "Мой iMac приехал сегодня утром! Я в восторге!!!",
        commentName6: "Beatrice Appiah",
        commentText6: "Я выиграла iPad. Я до сих пор не могу поверить в это!",
        commentName7: "Ranvin Hazam",
        commentText7: "Я выиграл ipad, но у меня он уже есть, можно ли поменять свой приз на iMac?",
        show_next: "Посмотреть всё",
        placeholder: "Ваше сообщение",
        modalMessage: "У Вас есть еще одна дополнительная попытка",
        btnModal: "Попробуйте еще раз",
        congratulationTitle2: "Поздравляем!",
        congratulationSubtitle2: "Вы выиграли суперприз!",
        condition:
            "Вам необходимо заполнить форму регистрации, для того чтобы получить Ваш приз, иначе он будет аннулирован.",
        conditionTitle: "ВАЖНАЯ ИНФОРМАЦИЯ: ",
        conditions2: "Призы могут закончиться в любой момент, выбирайте скорей!",
        timeTitle: "Предложение действительно ещё",
        minutes: "минут",
        seconds: "секунд",
        prize1Title: "Приз №1",
        prize2Title: "Приз №2",
        prizePriceCommon: "Обычная цена:",
        prizePriceYour: "Ваша цена:",
        prizeAvailable: "Доступно:",
        btnChoose: "Выбрать",
    },
    uk: {
        headline: "ПРОГРАМА ЛОЯЛЬНОСТІ",
        congratulationTitle: "Вітаємо!",
        congratulationSubtitle: "Сьогодні Ваш день!",
        intro: "Ми обираємо учасників, та даруємо їм можливість виграти призи від наших спонсорів. Крути колесо, щоб побачити свій подарунок!",
        btnSpin: "Поштовх",
        totalLikes: "людям це сподобалось",
        likeWord: "Лайк",
        commentWord: "Коментар",
        commentName1: "Parjapat Sunil",
        commentText1: "Випав Samsung Galaxy S9! Щиро кажучи, я хотів iMac, однак не сьогодні ...",
        itemDate1: "Вчора в 8:13",
        commentName2: "Sahil John",
        commentText2: "Я отримав 1 фрі спін, але не виграв приз. Чи можу я отримати ще один шанс?",
        commentName3: "Parmar Mahesh",
        commentText3: "Я щойно розпакував новий iMac! Це найкращий приз з усіх!",
        commentName4: "Doan Ha",
        commentText4:
            "Спочатку я подумав, що це жарт, але сьогодні вранці мені принесли новий Samsung Galaxy S9, а також футболку з логотипом!",
        commentName5: "Alexis Shane",
        commentText5: "Мій iMac приїхав сьогодні вранці! Я в захваті!!!",
        commentName6: "Beatrice Appiah",
        commentText6: "Я виграла iPad. Я й досі не можу в це повірити!",
        commentName7: "Ranvin Hazam",
        commentText7: "Я виграв ipad, але у мене вже є він, чи можна обміняти свій приз на iMac?",
        show_next: "Подивитись все",
        placeholder: "Ваше повідомлення",
        modalMessage: "Ви маєте ще одну додаткову спробу",
        btnModal: "Спробуйте ще",
        congratulationTitle2: "Вітаємо!",
        congratulationSubtitle2: "Ви виграли суперприз!",
        condition:
            "Вам потрібно заповнити форму реєстрації, для того щоб отримати Ваш приз, в іншому випадку, його буде анульовано.",
        conditionTitle: "ВАЖЛИВА ІНФОРМАЦІЯ: ",
        conditions2: "Подарунки можуть закінчитися в будь-який момент, обирайте хутчіш!",
        timeTitle: "Пропозиція дійсна ще",
        minutes: "хвилин",
        seconds: "секунд",
        prize1Title: "Приз №1",
        prize2Title: "Приз №2",
        prizePriceCommon: "Звичайна ціна:",
        prizePriceYour: "Ваша ціна:",
        prizeAvailable: "Доступно:",
        btnChoose: "Обрати",
    },
    ro: {
        headline: "PROGRAM DE FIDELIZARE",
        congratulationTitle: "Felicitări!",
        congratulationSubtitle: "Astăzi ești norocos!",
        intro: "Alegem utilizatorii pentru a le oferi posibilitatea de a câștiga premii de la sponsorii noștri. Rotiți roata pentru a vedea care premiul vei primi!",
        btnSpin: "Push",
        totalLikes: "oameni ca acest lucru",
        likeWord: "Apreciere",
        commentWord: "Comentariu",
        commentName1: "Parjapat Sunil",
        commentText1: "A scăzut Samsung Galaxy S9! Sincer, am vrut iMac, dar nu azi ...",
        itemDate1: "Ieri la 08:13",
        commentName2: "Sahil John",
        commentText2:
            "Am câștigat o rotire liberă, dar nu am câștigat un premiu. Pot obține o altă șansă?",
        commentName3: "Parmar Mahesh",
        commentText3: "Tocmai am despachetat noul iMac! Acesta este cel mai bun premiu al tuturor!",
        commentName4: "Doan Ha",
        commentText4:
            "La început am crezut că a fost o glumă, dar în această dimineață am fost dat un nou Samsung Galaxy S9, am primit, de asemenea, un tricou cu un logo!",
        commentName5: "Alexis Shane",
        commentText5: "IMac meu a sosit în această dimineață! Imi place!!!",
        commentName6: "Beatrice Appiah",
        commentText6: "Am câștigat iPad. Eu încă nu cred că acest lucru este adevărat!",
        commentName7: "Ranvin Hazam",
        commentText7: "Am câștigat iPad, dar am deja, pot schimba premiul pe iMac?",
        show_next: "Vezi toate",
        placeholder: "Mesajul tau",
        modalMessage: "Ai 1 rotire suplimentară",
        btnModal: "Încearcă din nou",
        congratulationTitle2: "Felicitări!",
        congratulationSubtitle2: "Ai câștigat un super premiu!",
        condition:
            "Va trebui să completați formularul de depunere a premiului sau premiul dvs. va fi pierdut.",
        conditionTitle: "IMPORTANT: ",
        conditions2: "Cadourile se pot încheia oricând, alegeți mai repede!",
        timeTitle: "Oferta valabilă pentru",
        minutes: "minute",
        seconds: "secunde",
        prize1Title: "Premiul №1",
        prize2Title: "Premiul №2",
        prizePriceCommon: "Preț comun:",
        prizePriceYour: "Prețul tău:",
        prizeAvailable: "Disponibil:",
        btnChoose: "Alege",
    },
    vi: {
        headline: "CHƯƠNG TRÌNH LOYALTY",
        congratulationTitle: "Xin chúc mừng!",
        congratulationSubtitle: "Hôm nay bạn là người may mắn!",
        intro: "Chúng tôi chọn người sử dụng để cung cấp cho họ cơ hội để giành chiến thắng giải thưởng từ nhà tài trợ của chúng tôi. Xoay bánh xe để xem những giải thưởng bạn sẽ nhận được!",
        btnSpin: "Push",
        totalLikes: "người như thế này",
        likeWord: "Thích",
        commentWord: "Bình luận",
        commentName1: "Parjapat Sunil",
        commentText1:
            "Giảm Samsung Galaxy S9! Thành thực mà nói, tôi muốn iMac, nhưng không phải hôm nay ...",
        itemDate1: "Hôm qua lúc 08:13",
        commentName2: "Sahil John",
        commentText2:
            "Tôi giành được 1 quay miễn phí, nhưng tôi đã không giành được một giải thưởng. Tôi có thể lấy một cơ hội khác?",
        commentName3: "Parmar Mahesh",
        commentText3: "Tôi chỉ giải nén iMac mới! Đây là giải thưởng tốt nhất của tất cả!",
        commentName4: "Đoàn Hà",
        commentText4:
            "Tại lần đầu tiên tôi nghĩ đó là một trò đùa, nhưng sáng nay tôi đã đưa ra một Samsung Galaxy mới S9, tôi cũng có một T-shirt với logo!",
        commentName5: "Alexis Shane",
        commentText5: "My iMac đến sáng nay! Tôi thích nó!!!",
        commentName6: "Beatrice Appiah",
        commentText6: "Tôi giành được iPad. Tôi vẫn không tin rằng đây là sự thật!",
        commentName7: "Ranvin Hazam",
        commentText7:
            "Tôi giành được ipad, nhưng tôi đã có nó, tôi có thể thay đổi các giải thưởng trên iMac?",
        show_next: "Nhìn thấy tất cả",
        placeholder: "Tin nhắn của bạn",
        modalMessage: "Bạn có thêm 1 vòng quay",
        btnModal: "Thử lại",
        congratulationTitle2: "Xin chúc mừng!",
        congratulationSubtitle2: "Bạn đã giành được một giải thưởng siêu!",
        condition:
            "Bạn sẽ cần phải hoàn thành mẫu đệ trình giải thưởng hoặc giải thưởng của bạn sẽ bị mất.",
        conditionTitle: "QUAN TRỌNG: ",
        conditions2: "Quà tặng có thể kết thúc bất cứ lúc nào, chọn nhanh hơn!",
        timeTitle: "Ưu đãi có giá trị cho",
        minutes: "phút",
        seconds: "giây",
        prize1Title: "Giải thưởng №1",
        prize2Title: "Giải 2",
        prizePriceCommon: "Giá chung:",
        prizePriceYour: "Giá trị của bạn:",
        prizeAvailable: "Có sẵn:",
        btnChoose: "Chọn",
    },
    cs: {
        headline: "VĚRNOSTNÍ PROGRAM",
        congratulationTitle: "Gratulujeme!",
        congratulationSubtitle: "Dnes budete mít štěstí!",
        intro: "Vybíráme uživatelům dát jim možnost vyhrát ceny od našich sponzorů. Otáčení volantem a zjistěte, které cenu získáte!",
        btnSpin: "Push",
        totalLikes: "takoví lidé",
        likeWord: "Líbí se mi",
        commentWord: "Komentář",
        commentName1: "Parjapat Sunil",
        commentText1: "Klesl Samsung Galaxy S9! Upřímně řečeno, chtěl jsem iMac, ale dnes ne ...",
        itemDate1: "Včera v 08:13",
        commentName2: "Sahil John",
        commentText2:
            "Vyhrál jsem 1 volný spin, ale neměl jsem vyhrát cenu. Mohu dostat další šanci?",
        commentName3: "Parmar Mahesh",
        commentText3: "Jen jsem vybalil nový iMac! To je nejlepší cenu ze všech!",
        commentName4: "Doan Ha",
        commentText4:
            "Nejdřív jsem si myslel, že je to vtip, ale dnes ráno jsem byl dodán nový Samsung Galaxy S9, také mám tričko s logem!",
        commentName5: "Alexis Shane",
        commentText5: "My iMac dorazil dnes ráno! Miluji to!!!",
        commentName6: "Beatrice Appiah",
        commentText6: "Vyhrál jsem iPad. Pořád nevěřím, že je to pravda!",
        commentName7: "Ranvin Hazam",
        commentText7: "Vyhrál jsem iPad, ale už mám to, mohu změnit cenu na iMac?",
        show_next: "Vidět vše",
        placeholder: "Vaše zpráva",
        modalMessage: "Máte 1 navíc spin",
        btnModal: "Zkus to znovu",
        congratulationTitle2: "Gratulujeme!",
        congratulationSubtitle2: "Vyhrál jsi super cenu!",
        condition: "Budete muset vyplnit formulář prize podání nebo vaše výhra propadá.",
        conditionTitle: "DŮLEŽITÉ: ",
        conditions2: "Dary může skončit kdykoliv zvolit rychlejší!",
        timeTitle: "Nabídka platí pro",
        minutes: "minut",
        seconds: "sekundy",
        prize1Title: "Cenu №1",
        prize2Title: "Cenu №2",
        prizePriceCommon: "Běžná cena:",
        prizePriceYour: "Tvá cena:",
        prizeAvailable: "Dostupný:",
        btnChoose: "Vybrat",
    },
    sr: {
        headline: "ПРОГРАМ ЛОЈАЛНОСТИ",
        congratulationTitle: "Честитам!",
        congratulationSubtitle: "Данас имате среће!",
        intro: "Ми смо изабрали корисницима да им се пружи могућност да освоје награде од наших спонзора. Окрените точак да бисте видели која награда добићете!",
        btnSpin: "Гурај",
        totalLikes: "пеопле лике тхис",
        likeWord: "Као",
        commentWord: "коментар",
        commentName1: "Парјапат Сунил",
        commentText1: "Пао Галаки С9! Искрено, желео сам да иМац, али не данас ...",
        itemDate1: "Јуче у 08:13",
        commentName2: "сахил Џон",
        commentText2:
            "Освојио сам 1 фрее спин, али нисам освојио награду. Могу ли добити још једну шансу?",
        commentName3: "пармар Махеш",
        commentText3: "Управо сам распаковао нови иМац! Ово је најбоља награда за све!",
        commentName4: "доан ха",
        commentText4:
            "У почетку сам мислио да је то шала, али јутрос сам био достављен нови Галаки С9 такође имам мајицу са логом!",
        commentName5: "Алексис Шејн",
        commentText5: "Мој МацБоок стигао јутрос! Свиђа ми се!!!",
        commentName6: "беатрице Апија",
        commentText6: "Сам добио иПад. И даље не верујем да је то истина!",
        commentName7: "Ранвин Хазам",
        commentText7: "Добио сам иПад, али већ сам га, могу да променим награду на иМац?",
        show_next: "Видети све",
        placeholder: "Ваша порука",
        modalMessage: "Имате 1 додатни спин",
        btnModal: "Покушајте поново",
        congratulationTitle2: "Честитам!",
        congratulationSubtitle2: "Освојили сте супер награду!",
        condition: "Морате попунити образац за пријаву награда или ће ваша награда бити одузета.",
        conditionTitle: "ВАЖНО: ",
        conditions2: "Поклони се могу завршити било када, одаберите брже!",
        timeTitle: "Понуда важи за",
        minutes: "минута",
        seconds: "секунди",
        prize1Title: "Награда №1",
        prize2Title: "Награда №2",
        prizePriceCommon: "Заједничка цена:",
        prizePriceYour: "Ваша цена:",
        prizeAvailable: "На располагању:",
        btnChoose: "Изаберите",
    },
    fa: {
        headline: "برنامه وفاداری",
        congratulationTitle: "تبریک می گویم!",
        congratulationSubtitle: "امروز شما خوش شانس!",
        intro: "ما را انتخاب کنید کاربران به آنها این فرصت را برای برنده شدن جوایز از حامیان مالی ما است. روشن کردن چرخ برای دیدن که جایزه شما دریافت خواهد کرد!",
        btnSpin: "فشار",
        totalLikes: " نفر این",
        likeWord: "مانند",
        commentWord: "نظر",
        commentName1: "Parjapat سونیل",
        commentText1:
            "کاهش یافته است سامسونگ Galaxy S9! راستش، من می خواستم به iMac، اما نه امروز ...",
        itemDate1: "دیروز در 08:13",
        commentName2: "ساحل جان",
        commentText2:
            "من برنده 1 چرخش آزاد، اما من یک جایزه برنده نیست. آیا من می توانم فرصت دیگری را دریافت کنم؟",
        commentName3: "پارمار ماهش",
        commentText3: "من فقط غیر بستهای iMac جدید! این بهترین جایزه از همه است!",
        commentName4: "دوان هکتار",
        commentText4:
            "در اول فکر کردم آن را یک شوخی بود، اما امروز صبح من یک کهکشان سامسونگ S9 جدید تحویل داده شد، من هم یک تی شرت با آرم!",
        commentName5: "الکسیس شین",
        commentText5: "من مانیتور وارد امروز صبح! عاشقشم!!!",
        commentName6: "بئاتریس آپیا",
        commentText6: "من برنده اپل. من هنوز هم باور نمی کنم که این درست است!",
        commentName7: "Ranvin از Hazam",
        commentText7:
            "من برنده اپل، اما من در حال حاضر آن را دارند، می توانید جایزه در مانیتور را عوض کنم؟",
        show_next: "همه را ببین",
        placeholder: "پیغام تو",
        modalMessage: "شما یک چرخش اضافی دارید",
        btnModal: "دوباره امتحان کنید",
        congratulationTitle2: "تبریک می گویم!",
        congratulationSubtitle2: "شما برنده یک جایزه فوق العاده!",
        condition: "شما باید فرم ارسال جایزه را تکمیل کنید یا جایزه شما از بین می رود.",
        conditionTitle: "مهم: ",
        conditions2: "هدیه می تواند در هر زمان به پایان برسد ، سریعتر را انتخاب کنید!",
        timeTitle: "پیشنهاد معتبر برای",
        minutes: "دقایق",
        seconds: "ثانیه",
        prize1Title: "جایزه №1",
        prize2Title: "جایزه №2",
        prizePriceCommon: "قیمت مشترک",
        prizePriceYour: "قیمت شما",
        prizeAvailable: "در دسترس",
        btnChoose: "انتخاب کنید",
    },
    az: {
        headline: "SADİQLİK PROQRAMI",
        congratulationTitle: "Təbrik edirik!",
        congratulationSubtitle: "Bu gün xoşbəxt edir!",
        intro: "Biz onlara sponsorlarımızdan hədiyyələr qazanmaq imkanı vermək üçün istifadəçilər seçin. Siz alacaq olan mükafat görmək üçün tam dönün!",
        btnSpin: "Push",
        totalLikes: "bunu bəyənir nəfər",
        likeWord: "Like",
        commentWord: "Comment",
        commentName1: "Parjapat Sunil",
        commentText1: "Azalıb Samsung Galaxy S9! Sözün düzü, mən bu gün iMac istəyirdi, lakin ...",
        itemDate1: "08:13 Dünən",
        commentName2: "Sahil John",
        commentText2:
            "I 1 pulsuz spin qazandı, amma bir mükafat qazana bilmədi. Mən bir şans əldə edə bilərsiniz?",
        commentName3: "Parmar Mahesh",
        commentText3: "Mən yalnız yeni iMac unpacked! Bu, bütün ən yaxşı mükafatdır!",
        commentName4: "Doan Ha",
        commentText4:
            "ilk I o bir zarafat olduğunu düşündü, amma yeni Samsung Galaxy S9 təslim edildi Bu gün səhər mən də bir logo ilə T-shirt var!",
        commentName5: "Alexis Shane",
        commentText5: "My iMac bu səhər gəlib! Mən onu sevirəm !!!",
        commentName6: "Beatrice Appiah",
        commentText6: "Mən iPad qazandı. Mən hələ bu doğru olduğunu inanmıram!",
        commentName7: "Ranvin Hazam",
        commentText7: "Mən iPad qazandı, amma artıq mən iMac mükafat dəyişə bilərsiniz var?",
        show_next: "Hamısını gör",
        placeholder: "Sənin mesajın",
        modalMessage: "1 əlavə spin var",
        btnModal: "Yenidən cəhd elə",
        congratulationTitle2: "Təbrik edirik!",
        congratulationSubtitle2: "Super mükafat qazandınız!",
        condition:
            "Mükafat təqdim etmə formasını doldurmalısınız və ya mükafatınız əldən veriləcəkdir.",
        conditionTitle: "Vacibdir: ",
        conditions2: "Hədiyyələr istədiyiniz vaxt bitə bilər, daha sürətli seçin",
        timeTitle: "Təklif etibarlıdır",
        minutes: "dəqiqə",
        seconds: "saniyə",
        prize1Title: "№1 mükafat",
        prize2Title: "Mükafat №2",
        prizePriceCommon: "Ümumi qiymət:",
        prizePriceYour: "Qiymətiniz:",
        prizeAvailable: "Mövcuddur:",
        btnChoose: "Seçin",
    },
    hr: {
        headline: "PROGRAM ODANOSTI",
        congratulationTitle: "Čestitamo!",
        congratulationSubtitle: "Danas ste sretni!",
        intro: "Mi odabiremo korisnik je dati im priliku za osvajanje nagrade od naših sponzora. Okrenite kotačić kako bi vidjeli koji nagradu ćete dobiti!",
        btnSpin: "Push",
        totalLikes: "ljudi kao što je ovaj",
        likeWord: "Kao i",
        commentWord: "komentar",
        commentName1: "Parjapat Sunil",
        commentText1: "Pao Samsung Galaxy S9! Iskreno, htio sam iMac, ali ne danas ...",
        itemDate1: "Jučer u 08:13",
        commentName2: "Sahil John",
        commentText2:
            "Dobio sam 1 besplatno spin, ali nisam osvojiti nagradu. Mogu li dobiti još jednu šansu?",
        commentName3: "Parmar Mahesh",
        commentText3: "Samo sam raspakirao novi iMac! Ovo je najbolja nagrada za sve!",
        commentName4: "Doan Ha",
        commentText4:
            "Isprva sam mislio da je šala, ali jutros sam bio dostavljen novi Samsung Galaxy S9, također sam dobio majicu s logom!",
        commentName5: "Alexis Shane",
        commentText5: "Moj iMac stigao jutros! Volim to!!!",
        commentName6: "Beatrice Appiah",
        commentText6: "Osvojio sam ipad. Ja još uvijek ne vjerujem da je to istina!",
        commentName7: "Ranvin Hazam",
        commentText7: "Osvojio sam ipad, ali već sam ga, mogu promijeniti nagradu na iMacu?",
        show_next: "Vidi sve",
        placeholder: "Tvoja poruka",
        modalMessage: "Imate 1 dodatni spin",
        btnModal: "Pokušajte ponovo",
        congratulationTitle2: "Čestitamo!",
        congratulationSubtitle2: "Osvojili ste super nagradu!",
        condition:
            "Trebat ćete ispuniti obrazac za prijavu nagrada ili će vaša nagrada biti oduzeta.",
        conditionTitle: "VAŽNO: ",
        conditions2: "Pokloni se mogu završiti bilo kada, odaberite brže!",
        timeTitle: "Ponuda vrijedi za",
        minutes: "minuta",
        seconds: "sekundi",
        prize1Title: "Nagrada №1",
        prize2Title: "Nagrada №2",
        prizePriceCommon: "Zajednička cijena:",
        prizePriceYour: "Tvoja cijena:",
        prizeAvailable: "Dostupno:",
        btnChoose: "izabrati",
    },
    hu: {
        headline: "HŰSÉGPROGRAM",
        congratulationTitle: "Gratulálunk!",
        congratulationSubtitle: "Ma szerencséd van!",
        intro: "Kiválasztjuk felhasználók adni nekik a lehetőséget, hogy nyerni díjakat a mi támogatóink. A vezérlőtárcsa elforgatásával, hogy melyik nyereményt kap!",
        btnSpin: "nyomás",
        totalLikes: "ember kedveli ezt",
        likeWord: "Mint",
        commentWord: "Hozzászólás",
        commentName1: "Parjapat Sunil",
        commentText1:
            "Eldobott Samsung Galaxy S9! Őszintén szólva, én akartam az iMac, de nem ma ...",
        itemDate1: "Yesterday at 08:13",
        commentName2: "Sahil John",
        commentText2: "Nyertem 1 ingyenes spin, de nem nyertem egy díjat. Kaphatok még egy esélyt?",
        commentName3: "Parmar Mahesh",
        commentText3: "Csak kicsomagolta az új iMac! Ez a legjobb díjat minden!",
        commentName4: "Doan Ha",
        commentText4:
            "Eleinte azt hittem, hogy ez egy vicc, de ma reggel hozta az új Samsung Galaxy S9, én is kaptam egy pólót a logó!",
        commentName5: "Alexis Shane",
        commentText5: "Saját iMac érkezett ma reggel! Szeretem!!!",
        commentName6: "Beatrice Appiah",
        commentText6: "Megnyertem az iPad. Még mindig nem hiszem, hogy ez igaz!",
        commentName7: "Ranvin Hazam",
        commentText7: "Megnyertem a ipad, de már van rá, tudom megváltoztatni a díjat az iMac?",
        show_next: "Az összes",
        placeholder: "Az üzeneted",
        modalMessage: "1 extra centrifugálásod van",
        btnModal: "Próbáld újra",
        congratulationTitle2: "Gratulálunk!",
        congratulationSubtitle2: "Szuper díjat nyertél!",
        condition:
            "Önnek ki kell töltenie a nyeremény benyújtási űrlapját, különben a díjat elveszítik.",
        conditionTitle: "FONTOS: ",
        conditions2: "Az ajándékok bármikor véget vethetnek, gyorsabban válasszanak!",
        timeTitle: "Ajánlat érvényes:",
        minutes: "percek",
        seconds: "másodperc",
        prize1Title: "№1 díj",
        prize2Title: "№2 díj",
        prizePriceCommon: "Közös ár:",
        prizePriceYour: "A te árad:",
        prizeAvailable: "Elérhető:",
        btnChoose: "Választ",
    },
    zh: {
        headline: "獎勵計畫",
        congratulationTitle: "恭喜！",
        congratulationSubtitle: "今天您很幸運！",
        intro: "我們隨機抽選用戶，將有機會從我們的贊助商那裡贏得獎品。轉動轉盤，看看您將獲得哪個獎品！",
        btnSpin: "按此",
        totalLikes: "people like this",
        likeWord: "Like",
        commentWord: "Comment",
        commentName1: "Parjapat Sunil",
        commentText1: "Dropped Samsung Galaxy S9! Honestly, I wanted the iMac, but not today ...",
        itemDate1: "Yesterday at 08:13",
        commentName2: "Sahil John",
        commentText2: "I won 1 free spin, but I did not win a prize. Can I get another chance?",
        commentName3: "Parmar Mahesh",
        commentText3: "I just unpacked the new iMac! This is the best prize of all!",
        commentName4: "Doan Ha",
        commentText4:
            "At first I thought it was a joke, but this morning I was delivered a new Samsung Galaxy S9, I also got a T-shirt with a logo!",
        commentName5: "Alexis Shane",
        commentText5: "My iMac arrived this morning! I love it!!!",
        commentName6: "Beatrice Appiah",
        commentText6: "I won the iPad. I still do not believe that this is true!",
        commentName7: "Ranvin Hazam",
        commentText7: "I won the ipad, but I already have it, can I change the prize on the iMac?",
        show_next: "See all",
        placeholder: "Your message",
        modalMessage: "你有 1 次額外旋轉機會",
        btnModal: "再試一次",
        congratulationTitle2: "恭喜！",
        congratulationSubtitle2: "",
        condition: "您需要填寫獎品提交表，否則您的獎品將會被沒收。",
        conditionTitle: "重要提示：",
        conditions2: "禮物隨時會結束，動作要快！",
        timeTitle: "優惠有效期為",
        minutes: "分",
        seconds: "秒",
        prize1Title: "獎項 №1",
        prize2Title: "獎項 №2",
        prizePriceCommon: "市價: ",
        prizePriceYour: "折扣後您的價格:",
        prizeAvailable: "剩餘:",
        btnChoose: "選擇",
    },
    it: {
        headline: "PROGRAMMA FEDELTÀ",
        congratulationTitle: "Congratulazioni!",
        congratulationSubtitle: "Oggi è il tuo giorno fortunato!",
        intro: "Selezioneremo utenti per dare loro l'opportunità di vincere tanti premi dei nostri sponsor. Gira la ruota per vedere quale premio ti toccherà!",
        btnSpin: "Premi",
        totalLikes: "persone piace questo elemento",
        likeWord: "Mi piace",
        commentWord: "Commenta",
        commentName1: "Parjapat Sunil",
        commentText1:
            "Ho vinto un Samsung Galaxy S9! Onestamente, volevo un iMac, ma oggi è andata così...",
        itemDate1: "Ieri alle 08:13",
        commentName2: "Sahil John",
        commentText2:
            "Ho vinto 1 giro gratis, ma non ho vinto nessun premio. Posso avere un'altra possibilità?",
        commentName3: "Parmar Mahesh",
        commentText3: "Ho appena ricevuto il nuovo iMac! È il miglior premio di tutti!",
        commentName4: "Doan Ha",
        commentText4:
            "All'inizio ho pensato che fosse uno scherzo, ma questa mattina mi è stato consegnato il nuovo Samsung Galaxy S9, ho anche ricevuto una maglietta con un logo!",
        commentName5: "Alexis Shane",
        commentText5: "Il mio iMac è arrivato stamattina! Lo adoro!!!",
        commentName6: "Beatrice Appiah",
        commentText6: "Ho vinto un iPad. Non posso ancora credere che sia vero!",
        commentName7: "Ranvin Hazam",
        commentText7: "Ho vinto un iPad, ma già ce l'ho, posso cambiare il premio con un iMac?",
        show_next: "Visualizza tutto",
        placeholder: "Il tuo messaggio",
        modalMessage: "Hai 1 giro extra",
        btnModal: "Riprova",
        congratulationTitle2: "Congratulazioni!",
        congratulationSubtitle2: "Hai vinto un super premio!",
        condition: "Dovrai compilare il modulo di invio del premio o lo perderai.",
        conditionTitle: "IMPORTANTE: ",
        conditions2: "I regali possono finire in qualsiasi momento, scegli velocemente!",
        timeTitle: "Offerta valida per",
        minutes: "minuti",
        seconds: "secondi",
        prize1Title: "Premio №1",
        prize2Title: "Premio №2",
        prizePriceCommon: "Prezzo comune:",
        prizePriceYour: "Il tuo prezzo:",
        prizeAvailable: "Disponibile:",
        btnChoose: "Scegli",
    },
    nl: {
        headline: "loyaliteitsprogramma",
        congratulationTitle: "Gefeliciteerd!",
        congratulationSubtitle: "Vandaag heb je mazzel!",
        intro: "We selecteren gebruikers en geven hen de kans om",
        btnSpin: "duwen",
        totalLikes: "mensen vonden dit leuk",
        likeWord: "Vind ik Leuk",
        commentWord: "Reageer",
        commentName1: "Parjapat Sunil",
        commentText1: "De Galaxy S9 gewonnen. Ik wilde eigenlijk de iMac, maar helaas.",
        itemDate1: "Gisteren, 08:13",
        commentName2: "Sahil John",
        commentText2: "Ik heb 1 gratis draai gewonnen, maar geen prijs. Krijg ik nog een kans?",
        commentName3: "Parmar Mahesh",
        commentText3: "Ik heb zojuist mijn nieuwe iMac uitgepakt! Dit is de beste prijs!",
        commentName4: "Doan Ha",
        commentText4:
            "Eerst dacht ik dat het een grap was, maar vanochtend werd mijn nieuwe Samsung Galaxy S9 bezorgd, en ik ontving ook een T-shirt met een logo!",
        commentName5: "Alexis Shane",
        commentText5: "Mijn iMac is vanochtend aangekomen! Supergaaf!!",
        commentName6: "Beatrice Appiah",
        commentText6: "Ik heb de iPad gewoonen, ik kan het nog steeds niet geloven!",
        commentName7: "Ranvin Hazam",
        commentText7:
            "Ik heb de iPad gewonnen maar heb al een iPad, kan ik deze ruilen voor een iMac?",
        show_next: "Bekijk allemaal",
        placeholder: "Jouw bericht",
        modalMessage: "Je hebt 1 extra draai",
        btnModal: "Probeer het opnieuw",
        congratulationTitle2: "Gefeliciteerd!",
        congratulationSubtitle2: "Je hebt een superprijs gewonnen!",
        condition:
            "U moet het formulier voor het indienen van prijzen invullen, anders vervalt uw prijs.",
        conditionTitle: "BELANGRIJK: ",
        conditions2: "Geschenken kunnen op elk moment eindigen, kies sneller!",
        timeTitle: "Aanbieding geldig voor",
        minutes: "minuten",
        seconds: "seconden",
        prize1Title: "Prijs №1",
        prize2Title: "Prijs №2",
        prizePriceCommon: "Gemeenschappelijke prijs:",
        prizePriceYour: "Jouw prijs:",
        prizeAvailable: "Beschikbaar:",
        btnChoose: "Kiezen",
    },
    es: {
        headline: "PROGRAMA DE FIDELIZACIÓN",
        congratulationTitle: "¡Enhorabuena!",
        congratulationSubtitle: "¡Hoy es tu día de suerte!",
        intro: "Hemos seleccionado a usuarios para darles la oportunidad de que ganen premios de nuestros anunciantes. ¡Gira la ruleta para ver qué premio te toca!",
        btnSpin: "Empujar",
        totalLikes: "personas les gusta esto",
        likeWord: "Me gusta",
        commentWord: "Comentar",
        commentName1: "Parjapat Sunil",
        commentText1: "¡Gané un Samsung Galaxy S9! Quería un iMac, pero hoy no pudo ser...",
        itemDate1: "Ayer a las 08:13",
        commentName2: "Sahil John",
        commentText2:
            "Gané 1 giro gratuito pero no me llevé ningún premio. ¿Puedo intentarlo otra vez?",
        commentName3: "Parmar Mahesh",
        commentText3: "Acabo de sacar mi nuevo iMac de la caja. ¡Es el mejor premio de todos!",
        commentName4: "Doan Ha",
        commentText4:
            "Al principio no me lo creía, pero esta mañana recibí un Samsung Galaxy S9. ¡También me enviaron una camiseta promocional!",
        commentName5: "Alexis Shane",
        commentText5: "¡Mi iMac llegó esta mañana! ¡Me encanta!",
        commentName6: "Beatrice Appiah",
        commentText6: "Gané un iPad. ¡Y todavía no me lo creo!",
        commentName7: "Ranvin Hazam",
        commentText7: "Gané el iPad, pero ya tengo uno. ¿Puedo cambiar el premio por un iMac?",
        show_next: "Ver todos",
        placeholder: "Tu mensaje",
        modalMessage: "Tienes un giro adicional",
        btnModal: "Inténtalo de nuevo",
        congratulationTitle2: "¡Enhorabuena!",
        congratulationSubtitle2: "¡Ganaste un premio increíble!",
        condition: "Tienes que rellenar el formulario de envío del premio o perderás tu premio.",
        conditionTitle: "IMPORTANTE: ",
        conditions2: "¡Los regalos se pueden acabar en cualquier momento, elige el tuyo rápido!",
        timeTitle: "Oferta válida durante",
        minutes: "minutos",
        seconds: "segundos",
        prize1Title: "Premio №1",
        prize2Title: "Premio №2",
        prizePriceCommon: "Premio más popular:",
        prizePriceYour: "Tu premio:",
        prizeAvailable: "Disponible:",
        btnChoose: "Elegir",
    },
    fr: {
        headline: "PROGRAMME DE FIDÉLITÉ",
        congratulationTitle: "Toutes nos félicitations !",
        congratulationSubtitle: "Aujourd'hui tu as de la chance !",
        intro: "Nous sélectionnons utilisateurs pour leur donner la possibilité de gagner des prix de nos sponsors. Tournez la roue pour voir quel prix vous recevrez !",
        btnSpin: "poussée",
        totalLikes: "personnes aiment ça",
        likeWord: "J'aime",
        commentWord: "Commenter",
        commentName1: "Parjapat Sunil",
        commentText1:
            "Tombé sur un Samsung Galaxy S9 ! Honnêtement, je voulais l'iMac, mais ce ne sera pas pour aujourd'hui...",
        itemDate1: "Hier à 08:13",
        commentName2: "Sahil John",
        commentText2:
            "J'ai gagné 1 tour de roue gratuit, mais je n'ai pas gagné de prix. Puis-je avoir une autre chance ?",
        commentName3: "Parmar Mahesh",
        commentText3: "Je viens de déballer le nouvel iMac ! C'est le meilleur prix de tous !",
        commentName4: "Doan Ha",
        commentText4:
            "Au début, je pensais que c'était une blague, mais ce matin, on m'a livré un nouveau Samsung Galaxy S9, et j'ai aussi reçu un T-shirt avec un logo !",
        commentName5: "Alexis Shane",
        commentText5: "Mon iMac est arrivé ce matin ! Je l'aime trop !!!",
        commentName6: "Beatrice Appiah",
        commentText6: "J'ai gagné l'iPad. Je n'y crois toujours pas !",
        commentName7: "Ranvin Hazam",
        commentText7:
            "J'ai gagné l'iPad, mais je l'ai déjà, puis-je changer ce prix contre un iMac ?",
        show_next: "Voir tout",
        placeholder: "Votre message",
        modalMessage: "Vous avez 1 tour de roue supplémentaire",
        btnModal: "Réessayer",
        congratulationTitle2: "Toutes nos félicitations !",
        congratulationSubtitle2: "Vous avez gagné un super prix !",
        condition: "Vous devrez remplir le formulaire de demande de prix ou votre prix sera perdu.",
        conditionTitle: "IMPORTANT : ",
        conditions2: "Les cadeaux peuvent se terminer à tout moment, choisissez plus vite !",
        timeTitle: "Offre valable pour",
        minutes: "minutes",
        seconds: "secondes",
        prize1Title: "Prix №1",
        prize2Title: "Prix №2",
        prizePriceCommon: "Prix ​​commun :",
        prizePriceYour: "Ton prix :",
        prizeAvailable: "Disponible :",
        btnChoose: "Choisir",
    },
    pl: {
        headline: "PROGRAM LOJALNOŚCIOWY",
        congratulationTitle: "Gratulacje!",
        congratulationSubtitle: "Dzisiaj masz szczęście!",
        intro: "Wybieramy użytkowników, aby dać im możliwość wygrania nagród od naszych sponsorów. Zakręć kołem, aby zobaczyć, jaką nagrodę otrzymasz!",
        btnSpin: "Push",
        totalLikes: "osób lubi to",
        likeWord: "Polub",
        commentWord: "Skomentuj",
        commentName1: "Parjapat Sunil",
        commentText1:
            "Dostałem Samsunga Galaxy S9! Szczerze mówiąc, chciałem iMaca, ale dziś się nie udało ...",
        itemDate1: "Wczoraj o 08:13",
        commentName2: "Sahil John",
        commentText2:
            "Wygrałem 1 darmowy obrót, ale nie wygrałem nagrody. Czy mogę dostać kolejną szansę?",
        commentName3: "Parmar Mahesh",
        commentText3: "Właśnie rozpakowałem nowy iMac! To najlepsza nagroda ze wszystkich!",
        commentName4: "Doan Ha",
        commentText4:
            "Na początku myślałem, że to żart, ale dziś rano dostałem nowy Samsung Galaxy S9, dostałem również koszulkę z logo!",
        commentName5: "Alexis Shane",
        commentText5: "Mój iMac przybył dziś rano! Uwielbiam to!!!",
        commentName6: "Beatrice Appiah",
        commentText6: "Wygrałem iPada. Nadal nie wierzę, że to prawda!",
        commentName7: "Ranvin Hazam",
        commentText7: "Wygrałem iPada, ale już go mam, czy mogę zmienić nagrodę na komputer iMac?",
        show_next: "Zobacz wszystko",
        placeholder: "Twoja wiadomość",
        modalMessage: "Masz 1 dodatkowy obrót",
        btnModal: "Spróbuj ponownie",
        congratulationTitle2: "Gratulacje!",
        congratulationSubtitle2: "Wygrałeś super nagrodę!",
        condition:
            "Musisz wypełnić formularz zgłoszenia nagrody, w przeciwnym razie nagroda przepadnie.",
        conditionTitle: "WAŻNE: ",
        conditions2: "Prezenty mogą zakończyć się w dowolnym momencie, wybierz szybciej!",
        timeTitle: "Oferta ważna przez",
        minutes: "minuty",
        seconds: "sekundy",
        prize1Title: "Nagroda №1",
        prize2Title: "Nagroda №2",
        prizePriceCommon: "Najczęstsza nagroda:",
        prizePriceYour: "Twoja nagroda:",
        prizeAvailable: "Dostępne:",
        btnChoose: "Wybierz",
    },
    tr: {
        headline: "SADAKAT PROGRAMI",
        congratulationTitle: "Tebrikler!",
        congratulationSubtitle: "Bugün şanslısınız!",
        intro: "Sponsorlarımızdan ödül kazanma fırsatı vermek için kullanıcı seçiyoruz. Çarkı çevirin ve ne kazandığınızı görün!",
        btnSpin: "Bas",
        totalLikes: "kişi bunu beğendi",
        likeWord: "Beğen",
        commentWord: "Yorum yap",
        commentName1: "Parjapat Sunil",
        commentText1:
            "Samsung Galaxy S9 kazandım! Açıkçası iMac istiyordum, ama o gün bugün değilmiş…",
        itemDate1: "Dün 08:13'te",
        commentName2: "Sahil John",
        commentText2:
            "1 ücretsiz çevirme hakkı kazandım, ama ödül kazanamadım. Bir şans daha alabilir miyim?",
        commentName3: "Parmar Mahesh",
        commentText3: "Yeni iMac'in paketini şimdi açtım! Şimdiye kadarki en iyi ödül!",
        commentName4: "Doan Ha",
        commentText4:
            "İlk başta şaka olduğunu düşündüm, ama bu sabah yeni bir Samsung Galaxy S9 teslim edildi, ayrıca logolu bir T-shirt'te geldi!",
        commentName5: "Alexis Shane",
        commentText5: "iMac'im bu sabah geldi! Onu çok sevdim!!!",
        commentName6: "Beatrice Appiah",
        commentText6: "iPad kazandım. Bunun doğru olduğuna halen inanamıyorum!",
        commentName7: "Ranvin Hazam",
        commentText7:
            "ipad kazandım, ama zaten ipad'im var, ödülümü iMac ile değiştirebilir miyim?",
        show_next: "Hepsini görün",
        placeholder: "Mesajınız",
        modalMessage: "1 ekstra dönüşünüz var",
        btnModal: "Tekrar deneyin",
        congratulationTitle2: "Tebrikler!",
        congratulationSubtitle2: "Süper bir ödül kazandınız!",
        condition: "Ödül teslim formunu doldurmanız gerekir, aksi takdirde ödülünüz kaybedilir.",
        conditionTitle: "ÖNEMLİ ",
        conditions2: "Hediyeler her zaman sona erebilir, daha hızlı seçin!",
        timeTitle: "Teklif için geçerli",
        minutes: "dakika",
        seconds: "saniye",
        prize1Title: "Ödül №1",
        prize2Title: "Ödül №2",
        prizePriceCommon: "Ortak fiyat:",
        prizePriceYour: "Senin fiyatin:",
        prizeAvailable: "Mevcut:",
        btnChoose: "Seç",
    },
    pt: {
        headline: "PROGRAMA DE FIDELIZAÇÃO",
        congratulationTitle: "Parabéns!",
        congratulationSubtitle: "Hoje está com sorte!",
        intro: "Selecionamos utilizadores para lhes dar a oportunidade de ganhar prémios dos nossos patrocinadores. Gire a roda para ver que prémio vai receber!",
        btnSpin: "Empurrar",
        totalLikes: "pessoas gostam disto",
        likeWord: "Gostar",
        commentWord: "Comentar",
        commentName1: "Parjapat Sunil",
        commentText1:
            "Calhou o Samsung Galaxy S9! Sinceramente, eu queria o iMac, mas não foi hoje...",
        itemDate1: "Ontem às 08:13",
        commentName2: "Sahil John",
        commentText2: "Ganhei 1 rodada grátis, mas não ganhei um prémio. Posso ter outra hipótese?",
        commentName3: "Parmar Mahesh",
        commentText3: "Acabei de desempacotar o novo iMac! Este é o melhor prémio de todos!",
        commentName4: "Doan Ha",
        commentText4:
            "No início, achei que era uma piada, mas esta manhã recebi um novo Samsung Galaxy S9, também recebi uma T-shirt com um logotipo!",
        commentName5: "Alexis Shane",
        commentText5: "O meu iMac chegou hoje de manhã! Adoro-o!!!",
        commentName6: "Beatrice Appiah",
        commentText6: "Eu ganhei o iPad. Ainda não acredito que isto seja verdade!",
        commentName7: "Ranvin Hazam",
        commentText7: "Ganhei o ipad, mas já tenho um, posso alterar o prémio para o iMac?",
        show_next: "Ver tudo",
        placeholder: "A sua mensagem",
        modalMessage: "Você tem 1 rodada extra",
        btnModal: "Tente novamente",
        congratulationTitle2: "Parabéns!",
        congratulationSubtitle2: "Você ganhou um super prêmio!",
        condition:
            "Você precisará preencher o formulário de envio do prêmio ou seu prêmio será perdido.",
        conditionTitle: "IMPORTANTE ",
        conditions2: "Os presentes podem terminar a qualquer momento, escolha mais rápido!",
        timeTitle: "Oferta válida para",
        minutes: "minutos",
        seconds: "segundos",
        prize1Title: "Prêmio №1",
        prize2Title: "Prêmio №2",
        prizePriceCommon: "Preço comum:",
        prizePriceYour: "Seu preço:",
        prizeAvailable: "acessível:",
        btnChoose: "Escolher",
    },
    th: {
        headline: "โปรแกรมความภักดี",
        congratulationTitle: "ขอแสดงความยินดี!",
        congratulationSubtitle: "วันนี้คุณโชคดี!",
        intro: "เราเลือกผู้ใช้ คนเพื่อให้พวกเขามีโอกาสชนะรางวัลจากผู้สนับสนุนของเรา หมุนวงล้อเพื่อดูว่าคุณจะได้รับรางวัลอะไร!",
        btnSpin: "ผลัก",
        totalLikes: "คนถูกใจสิ่งนี้",
        likeWord: "กดไลค์",
        commentWord: "คอมเม้นท์",
        commentName1: "Parjapat Sunil",
        commentText1: "ฉันได้ Samsung Galaxy S9! จริงๆแล้วฉันอยากได้ iMac แต่วันนี้ฉันไม่ได้...",
        itemDate1: "เมื่อวานนี้เวลา 08:13 น.",
        commentName2: "Sahil John",
        commentText2: "ฉันชนะและได้ 1 ฟรีสปินแต่ฉันไม่ชนะรางวัลอะไรเลยฉันขอโอกาสอีกครั้งได้ไหม?",
        commentName3: "Parmar Mahesh",
        commentText3: "ฉันเพิ่งแกะกล่อง iMac ใหม่! นี่คือรางวัลที่ดีที่สุดจากทั้งหมด!",
        commentName4: "Doan Ha",
        commentText4:
            "ตอนแรกฉันคิดว่ามันเป็นเรื่องตลกแต่เมื่อเช้านี้ฉันได้รับ Samsung Galaxy S9 ตัวใหม่และฉันก็ได้เสื้อยืดพร้อมโลโก้ด้วย!",
        commentName5: "Alexis Shane",
        commentText5: "iMac ของฉันมาถึงเมื่อเช้านี้! ฉันรักมัน!!!",
        commentName6: "Beatrice Appiah",
        commentText6: "ฉันชนะและได้ iPad มา ฉันยังไม่เชื่อเลยว่านี่มันคือเรื่องจริง!",
        commentName7: "Ranvin Hazam",
        commentText7:
            "ฉันได้รับรางวัลเป็น ipad แต่ฉันมีอยู่แล้ว ฉันสามารถเปลี่ยนรางวัลเป็น iMac ได้หรือไม่?",
        show_next: "ดูทั้งหมด",
        placeholder: "ข้อความของคุณ",
        modalMessage: "คุณมี 1 สปินเสริม",
        btnModal: "ลองอีกครั้ง",
        congratulationTitle2: "ขอแสดงความยินดี!",
        congratulationSubtitle2: "คุณชนะรางวัลใหญ่!",
        condition: "คุณจะต้องกรอกแบบฟอร์มการส่งรางวัลมิเช่นนั้นรางวัลของคุณจะถูกริบ",
        conditionTitle: "สำคัญ: ",
        conditions2: "ของขวัญสามารถสิ้นสุดได้ทุกเวลาเลือกเร็วขึ้น!",
        timeTitle: "ข้อเสนอที่ถูกต้องสำหรับ",
        minutes: "นาที",
        seconds: "วินาที",
        prize1Title: "รางวัล №1",
        prize2Title: "รางวัล №2",
        prizePriceCommon: "ราคาสามัญ:",
        prizePriceYour: "ราคาของคุณ:",
        prizeAvailable: "ที่มีจำหน่าย:",
        btnChoose: "เลือก",
    },
    de: {
        headline: "TREUEPROGRAMM",
        congratulationTitle: "Herzlichen Glückwunsch!",
        congratulationSubtitle: "Heute haben Sie Glück!",
        intro: "Wir wählen sieben Benutzer aus, denen wir die Möglichkeit geben, Preise von unseren Sponsoren zu gewinnen. Drehen Sie das Rad, um zu sehen, welchen Preis Sie erhalten könnten!",
        btnSpin: "Drücken",
        totalLikes: "Leuten gefällt das",
        likeWord: "Gefällt mir",
        commentWord: "Kommentar",
        commentName1: "Parjapat Sunil",
        commentText1:
            "Habe das Samsung Galaxy S9 nicht genommen! Ehrlich gesagt wollte ich das iMac, aber heute nicht…",
        itemDate1: "Gestern um 08:13",
        commentName2: "Sahil John",
        commentText2:
            "Ich habe eine kostenlose Drehung gewonnen, aber keinen Preis gewonnen. Kann ich noch eine Chance bekommen?",
        commentName3: "Parmar Mahesh",
        commentText3: "Ich habe gerade das neue iMac ausgepackt! Es ist der beste Preis von allen!",
        commentName4: "Doan Ha",
        commentText4:
            "Zuerst dachte ich, es sei ein Witz, aber heute Morgen wurde mir ein neues Samsung Galaxy S9 geliefert, ich bekam auch ein T-Shirt mit einem Logo!",
        commentName5: "Alexis Shane",
        commentText5: "Mein iMac ist heute Morgen angekommen! Ich liebe es!!!",
        commentName6: "Beatrice Appiah",
        commentText6: "Ich habe das iPad gewonnen. Ich glaube immer noch nicht, dass das wahr ist!",
        commentName7: "Ranvin Hazam",
        commentText7:
            "Ich habe das iPad gewonnen, aber ich habe bereits eins. Kann ich den Preis zu einem iMac ändern?",
        show_next: "Alles sehen",
        placeholder: "Ihre Nachricht",
        modalMessage: "Sie haben 1 zusätzlichen Spin",
        btnModal: "Versuchen Sie es nochmal",
        congratulationTitle2: "Herzlichen Glückwunsch!",
        congratulationSubtitle2: "Du hast einen super Preis gewonnen!",
        condition:
            "Sie müssen das Formular zur Einreichung des Preises ausfüllen, sonst verfällt Ihr Preis.",
        conditionTitle: "WICHTIG: ",
        conditions2: "Geschenke können jederzeit enden, wählen Sie schneller!",
        timeTitle: "Angebot gültig für",
        minutes: "Minuten",
        seconds: "Sekunden",
        prize1Title: "Preis №1",
        prize2Title: "Preis №2",
        prizePriceCommon: "Gemeinsamer Preis:",
        prizePriceYour: "Dein Preis:",
        prizeAvailable: "Verfügbar:",
        btnChoose: "Wählen",
    },
    da: {
        headline: "LOYALITETSPROGRAM",
        congratulationTitle: "Tillykke!",
        congratulationSubtitle: "I dag er du heldig!",
        intro: "Vi vælger syv brugere og giver dem muligheden for at vinde præmier fra vores sponsorer. Drej på hjulet for at se, hvilken pris du modtager!",
        btnSpin: "Skub",
        totalLikes: "mennesker synes om dette",
        likeWord: "Synes om",
        commentWord: "Kommenter",
        commentName1: "Parjapat Sunil",
        commentText1:
            "Tabte Samsung Galaxy S9! Helt ærligt, jeg ville have iMac, men ikke i dag ...",
        itemDate1: "I går kl. 08.13",
        commentName2: "Sahil John",
        commentText2:
            "Jeg vandt et gratis spin, men vandt ikke en præmie. Kan jeg få en chance til?",
        commentName3: "Parmar Mahesh",
        commentText3: "Jeg har lige pakket den nye iMac ud! Dette er den bedste præmie af alle!",
        commentName4: "Doan Ha",
        commentText4:
            "Først troede jeg, det var en joke, men i morges fik jeg en ny Samsung Galaxy S9. Jeg fik også en T-shirt med et logo!",
        commentName5: "Alexis Shane",
        commentText5: "Min iMac ankom i morges! Jeg elsker den!!!",
        commentName6: "Beatrice Appiah",
        commentText6: "Jeg vandt iPad. Jeg tror stadig ikke, at det virkelig passer!",
        commentName7: "Ranvin Hazam",
        commentText7: "Jeg vandt ipad, men jeg har allerede en. Kan jeg bytte præmien på iMac?",
        show_next: "Se alle",
        placeholder: "Din besked",
        modalMessage: "Du har 1 ekstra tur",
        btnModal: "Prøv igen",
        congratulationTitle2: "Tillykke!",
        congratulationSubtitle2: "Du har vundet en super præmie!",
        condition:
            "Du bliver nødt til at fuldføre præmie indsendelse form eller din gevinst vil blive annuleret.",
        conditionTitle: "VIGTIG: ",
        conditions2: "Gaver kan ende når som helst, vælge hurtigere!",
        timeTitle: "Tilbuddet gælder for",
        minutes: "minutters",
        seconds: "sekunders",
        prize1Title: "Præmie №1",
        prize2Title: "Præmie №2",
        prizePriceCommon: "Fælles pris:",
        prizePriceYour: "Din pris:",
        prizeAvailable: "Ledig:",
        btnChoose: "Vælge",
    },
    sv: {
        headline: "LOJALITETSPROGRAM",
        congratulationTitle: "Grattis!",
        congratulationSubtitle: "I dag har du tur!",
        intro: "Vi väljer ut användare för att erbjuda dem möjligheten att vinna priser från våra sponsorer. Vrid på ratten för att se vilket pris du kommer att få!",
        btnSpin: "Tryck",
        totalLikes: "personer gillar det här",
        likeWord: "Gilla",
        commentWord: "Kommentera",
        commentName1: "Parjapat Sunil",
        commentText1:
            "Tappade min Samsung Galaxy S9! Ärligt talat, jag ville ha iMac, men inte idag ...",
        itemDate1: "Igår klockan 08:13",
        commentName2: "Sahil John",
        commentText2: "Jag vann 1 gratissnurr, men vann ingen pris. Kan jag få en ny chans?",
        commentName3: "Parmar Mahesh",
        commentText3: "Jag packade precis upp den nya iMac:en! Detta är det bästa priset av alla!",
        commentName4: "Doan Ha",
        commentText4:
            "Först trodde jag att det var ett skämt, men i morse mottog jag en ny Samsung Galaxy S9. Jag fick också en T-shirt med tryckt logo!",
        commentName5: "Alexis Shane",
        commentText5: "Min iMac anlände i morse! Jag fullkomligt älskar den!!!",
        commentName6: "Beatrice Appiah",
        commentText6: "Jag vann en iPad! Jag tror fortfarande inte att detta är sant!",
        commentName7: "Ranvin Hazam",
        commentText7:
            "Jag vann en iPad, men äger redan en, kan jag ändra mitt pris till en iMac istället?",
        show_next: "Se allt",
        placeholder: "Ditt meddelande",
        modalMessage: "Du har en extra spinn",
        btnModal: "Försök igen",
        congratulationTitle2: "Grattis!",
        congratulationSubtitle2: "Du vann en super pris!",
        condition: "Du måste fylla i pris formulär eller ditt pris kommer att förverkas.",
        conditionTitle: "VIKTIG: ",
        conditions2: "Gåvor kan sluta när som helst genom att välja snabbare!",
        timeTitle: "Erbjudandet gäller för",
        minutes: "minuter",
        seconds: "sekunder",
        prize1Title: "Prize №1",
        prize2Title: "Prize №2",
        prizePriceCommon: "Gemensamt pris:",
        prizePriceYour: "Ditt pris:",
        prizeAvailable: "Tillgängliga:",
        btnChoose: "Välja",
    },
    ja: {
        headline: "ポイントプログラム",
        congratulationTitle: "おめでとうございます！",
        congratulationSubtitle: "今日のあなたはついてます！",
        intro: "スポンサーからの賞品が、7人のユーザーにあたります。何が当たるか、是非ご確認ください！",
        btnSpin: "Push",
        totalLikes: "人の人が、このようにコメントしています",
        likeWord: "いいね！",
        commentWord: "コメント",
        commentName1: "Parjapat Sunil",
        commentText1:
            "ギャラクシーS9が当たりました！ほんとはiMacが欲しかったんだけど、今日はだめだった・・・",
        itemDate1: "昨日8：13",
        commentName2: "Sahil John",
        commentText2: "1回無料券あたりました。賞品はだめだった。もう一回できるかな？",
        commentName3: "Parmar Mahesh",
        commentText3: "たった今、iMac開封しました！これ、最高の賞品だ！",
        commentName4: "Doan Ha",
        commentText4:
            "最初、冗談かなって思ってなんです。でも、今朝新品のサムソンギャラクシーS9が届いて。ロゴ入りTシャツももらいました！",
        commentName5: "Alexis Shane",
        commentText5: "オレのiMac、今朝届いたー！サイコー！！！",
        commentName6: "Beatrice Appiah",
        commentText6: "iPadが当たりました。これ、まだ信じられなんだけど！",
        commentName7: "Ranvin Hazam",
        commentText7:
            "ipadが当たりました。でも実はもう持ってるんだけど。iMacに変更ってできるのかな。",
        show_next: "すべて見る",
        placeholder: "あなたのメッセージ",
        modalMessage: "あなたは、1つの余分なスピンを持っています",
        btnModal: "再試行",
        congratulationTitle2: "おめでとう！",
        congratulationSubtitle2: "あなたはスーパー賞を受賞しました！",
        condition:
            "あなたは、賞品の送信フォームを完了する必要がありますか、あなたの賞金は没収されます。",
        conditionTitle: "重要： ",
        conditions2: "ギフトはより速く選択し、いつでも終了することができます！",
        timeTitle: "の有効なオファ",
        minutes: "分",
        seconds: "秒",
        prize1Title: "賞 №1",
        prize2Title: "賞 №2",
        prizePriceCommon: "共通価格：",
        prizePriceYour: "あなたの価格：",
        prizeAvailable: "利用可能：",
        btnChoose: "を選択し",
    },
    id: {
        headline: "PROGRAM LOYALTY",
        congratulationTitle: "Selamat!",
        congratulationSubtitle: "Kamu beruntung hari ini!",
        intro: "Kami memilih pengguna dan memberikan kesempatan memenangkan hadiah dari sponsor. Putar roletnya untuk melihat hadiah apa saja yang kamu dapatkan!",
        btnSpin: "Push",
        totalLikes: "orang memberi suka",
        likeWord: "Suka",
        commentWord: "Komen",
        commentName1: "Parjapat Sunil",
        commentText1:
            "Menolak Samsung Galaxy S9! Sejujurnya, saya kepingin mendapatkan iMac, tapi hari ini belum dapat ...",
        itemDate1: "Kemarin jam 08:13",
        commentName2: "Sahil John",
        commentText2:
            "Saya mendapatkan 1 putaran gratis, tapi tidak memenangkan hadiah apapun. Bisa tidak minta satu lagi?",
        commentName3: "Parmar Mahesh",
        commentText3: "Saya barusan membuka iMac baru! Hadiah terbaik dari segala hadiah!",
        commentName4: "Doan Ha",
        commentText4:
            "Pertamanya saya kira dikibulin, tapi tadi pagi saya dapat kiriman Samsung Galaxy S9 baru, ditambah T-shirt yang ada logonya!",
        commentName5: "Alexis Shane",
        commentText5: "iMac untuk saya sudah tiba tadi pagi! Suka banget!!!",
        commentName6: "Beatrice Appiah",
        commentText6: "Saya memenangkan iPad. Rasanya masih gak percaya, kayak mimpi aja!",
        commentName7: "Ranvin Hazam",
        commentText7:
            "Saya memenangkan ipad, tapi saya sudah punya, boleh tukar dengan iMac tidak?",
        show_next: "Lihat semua",
        placeholder: "Pesan kamu",
        modalMessage: "Anda memiliki 1 berputar ekstra",
        btnModal: "Coba lagi",
        congratulationTitle2: "Selamat!",
        congratulationSubtitle2: "Anda memenangkan hadiah super!",
        condition:
            "Anda akan perlu melengkapi formulir pengajuan hadiah atau hadiah Anda akan hangus. ",
        conditionTitle: "PENTING: ",
        conditions2: "Hadiah bisa berakhir kapan saja, memilih lebih cepat!",
        timeTitle: "Penawaran berlaku untuk",
        minutes: "menit",
        seconds: "detik",
        prize1Title: "Hadiah №1",
        prize2Title: "Hadiah №2",
        prizePriceCommon: "Harga umum:",
        prizePriceYour: "Harga Anda:",
        prizeAvailable: "Tersedia:",
        btnChoose: "Memilih",
    },
};
$(document).ready(function () {
    var langBrowser = navigator.language || (navigator.languages && navigator.languages[0]),
        param = langs[langBrowser];
    if (param == undefined && langBrowser && langBrowser.length > 0) {
        var parsedLang = langBrowser.slice(0, 2);
        if (langs[parsedLang]) {
            param = langs[parsedLang];
        }
    }
    //param = langs['uk'];
    if (param == undefined) {
        param = langs["en"];
        // 'en' - default language, if you want change language, please select in object abbreviation. Example: 'fr', 'ru' etc.
    } else {
        $(".headline").text(param.headline);
        $(".congratulationTitle").text(param.congratulationTitle);
        $(".congratulationSubtitle").text(param.congratulationSubtitle);
        $(".intro").text(param.intro);
        $(".btnSpin").text(param.btnSpin);
        $(".congratulationTitle2").text(param.congratulationTitle2);
        $(".congratulationSubtitle2").text(param.congratulationSubtitle2);
        $(".condition").text(param.condition);
        $(".conditionTitle").text(param.conditionTitle);
        $(".conditions2").text(param.conditions2);
        $(".timeTitle").text(param.timeTitle);
        $(".minutes").text(param.minutes);
        $(".seconds").text(param.seconds);
        $(".prize1Title").text(param.prize1Title);
        $(".prize2Title").text(param.prize2Title);
        $(".prizePriceCommon").text(param.prizePriceCommon);
        $(".prizePriceYour").text(param.prizePriceYour);
        $(".prizeAvailable").text(param.prizeAvailable);
        $(".btnChoose").text(param.btnChoose);
        $(".totalLikes").text(param.totalLikes);
        $(".likeWord").text(param.likeWord);
        $(".comment").text(param.commentWord);
        $(".commentName1").text(param.commentName1);
        $(".commentText1").text(param.commentText1);
        $(".itemDate1").text(param.itemDate1);
        $(".commentName2").text(param.commentName2);
        $(".commentText2").text(param.commentText2);
        $(".commentName3").text(param.commentName3);
        $(".commentText3").text(param.commentText3);
        $(".commentName4").text(param.commentName4);
        $(".commentText4").text(param.commentText4);
        $(".commentName5").text(param.commentName5);
        $(".commentText5").text(param.commentText5);
        $(".commentName6").text(param.commentName6);
        $(".commentText6").text(param.commentText6);
        $(".commentName7").text(param.commentName7);
        $(".commentText7").text(param.commentText7);
        $(".show_next").text(param.show_next);
        $(".footer_input").attr("placeholder", param.placeholder);
        $(".modalMessage").text(param.modalMessage);
        $(".btnModal").text(param.btnModal);
    }
});
